title = "High-Performance Async MySQL Driver for .NET"
baseurl = "https://mysqlconnector.net/"
MetaDataFormat = "yaml"
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsStyle = "friendly"
disablePathToLower = true

[blackfriday]
  plainIDAnchors = true

[params]
  description = "Documentation for MySqlConnector: an Async MySQL Driver for .NET and .NET Core"
  author = "MySqlConnector Authors"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = 20
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-lightbulb-o'></i>"
    weight = 40
[[menu.main]]
    name = "API"
    identifier = "api"
    pre = "<i class='fa fa-file-text'></i>"
    url = "/api/MySqlConnectorAssembly/"
    weight = 35
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-lightbulb-o'></i>"
    weight = 60
