[build]
base = "docs/"
publish = "docs/public/"
command = "hugo --gc --minify -v"

[[redirects]]
from = "/home/"
to = "/"
force = true

[[redirects]]
from = "/index.html"
to = "/"
force = true

[[redirects]]
from = "/:category/index.html"
to = "/:category/"
force = true

[[redirects]]
from = "/:category/:page/index.html"
to = "/:category/:page/"
force = true

[[redirects]]
from = "/api/"
to = "/api/MySqlConnectorAssembly/"
status = 302
force = true

[[redirects]]
from = "/api/mysql-batch/"
to = "/api/MySqlConnector/MySqlBatchType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-bulk-copy/"
to = "/api/MySqlConnector/MySqlBulkCopyType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-bulk-loader/"
to = "/api/MySqlConnector/MySqlBulkLoaderType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-command/"
to = "/api/MySqlConnector/MySqlCommandType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-connection/"
to = "/api/MySqlConnector/MySqlConnectionType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-data-reader/"
to = "/api/MySqlConnector/MySqlDataReaderType/"
status = 301
force = true

[[redirects]]
from = "/api/mysql-transaction/"
to = "/api/MySqlConnector/MySqlTransactionType/"
status = 301
force = true

[[redirects]]
from = "/groups/"
to = "/"
status = 302
force = true

[[redirects]]
from = "/overview/"
to = "/"
status = 302
force = true

[[redirects]]
from = "/tags/"
to = "/"
status = 302
force = true

[[redirects]]
from = "/troubleshooting/"
to = "/"
status = 302
force = true

[[redirects]]
from = "/tutorials/"
to = "/"
status = 302
force = true
